controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


mainPage:
    path: /userIn
    controller: App\Controller\index::index

    
sendMessage:
    path: /sendMessage
    controller: App\Controller\index::sendMessage

register:
    path: /register
    controller: App\Controller\UserController::register

login:
    path: /login
    controller: App\Controller\UserController::login


checkMessage:
    path: /message/{id}
    controller: App\Controller\index::checkMessage

deleteMessage:
    path: /deleteMessage/{id}
    controller: App\Controller\index::deleteMessage